from No import No
from AVL import AVL

biblioteca = AVL()

biblioteca.insertBook(40, 2000)
biblioteca.insertBook(15, 2002)
biblioteca.insertBook(80, 2005)
biblioteca.insertBook(10, 2005)
biblioteca.insertBook(23, 2005)
biblioteca.insertBook(60, 2005)
biblioteca.insertBook(100, 2005)
print(biblioteca.getRoot())
print(biblioteca.getRoot().getLeft())
print(biblioteca.getRoot().getRight())
print(biblioteca.getRoot().getLeft().getLeft())
print(biblioteca.getRoot().getLeft().getRight())
print(biblioteca.getRoot().getRight().getLeft())
print(biblioteca.getRoot().getRight().getRight())
print('-------------')
biblioteca.removeBook(100)
biblioteca.removeBook(80)
biblioteca.removeBook(15)
print(biblioteca.getRoot())
print(biblioteca.getRoot().getLeft())
print(biblioteca.getRoot().getRight())
print(biblioteca.getRoot().getLeft().getLeft())
print(biblioteca.getRoot().getLeft().getRight())
print(biblioteca.getRoot().getRight().getLeft())
print(biblioteca.getRoot().getRight().getRight())